platform :ios, '14.0'

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

project 'App/App.xcodeproj'

target 'App' do
  # Capacitor dependencies
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'NavigationBar', :path => '../../'
end
